### PR TITLE
Blog app - integration specs for views and fix n+1 problems

### PR DESCRIPTION
**Pull request by lojacho**
# In this pull request, We were able to: 

- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user, I don't have any N+1 problems, and I also use bullet gem in order to corroborate this. 

- Use Capybara to write integration tests for each view in your project.

## User index page:
Can see the username of all other users.
Can see the profile picture for each user.
Can see the number of posts each user has written.
When I click on a user, I am redirected to that user's show page.

## User show page:
Can see the user's profile picture.
Can see the user's username.
Can see the number of posts the user has written.
Can see the user's bio.
Can see the user's first 3 posts.
Can see a button that lets me view all of a user's posts.
When I click a user's post, it redirects me to that post's show page.
When I click to see all posts, it redirects me to the user's post's index page.

##User post index page:
Can see the user's profile picture.
Can see the user's username.
Can see the number of posts the user has written.
Can see a post's title.
Can see some of the post's body.
Can see the first comments on a post.
Can see how many comments a post has.
Can see how many likes a post has.
Can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.

##Post show page:
Can see the post's title.
Can see who wrote the post.
Can see how many comments it has.
Can see how many likes it has.
Can see the post body.
Can see the username of each commentor.
Can see the comment each commentor left.

Thanks for the revision
Diego

### CODE REVIEW

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @Team,





Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice Rspec test. ✔️
- Descriptive PR. ✔️
- Test passed :heavy_check_mark: 


## Required Changes ♻️
_Check the comments below._

- [ ] As a requirement for this project, let's not forget to solve the N+1 problem when fetching all posts and their comments for a user. In your [PostsController's](https://github.com/dgcuenca/Blog-app/blob/fd0e00f6c0dd9ac059e690b642c12be6adf157f3/app/controllers/posts_controller.rb#L2-L6) posts#index action, you should include the comments `@posts = @user.posts.includes(:comments)` to solve the N+1 problem. kindly fix this.



## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lojacho** [comment]
@zieeco Thanks for the review, if you read carefully my PR in the first bullet I wrote the next: " I don't have any N+1 problems, and I also use bullet gem in order to corroborate this.", that's why my coding partner @paulsaenzsucre  and me not implemented any N+1 fix and that's why I can not proceed to implement your required changes because there is nothing to implement. I also added the bullet gem so you can also see that I don't have any N+1 problem.

**Review by t-yanick — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED

Hi @dgcuenca and @paulsaenzsucre , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [x] As indicated by the previous reviewer, you have to solve the N+1 problem using `@posts = @user.posts.includes(:comments)` in the `post#index` action. 
- As you can see in the screenshot below from the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md), you are not to use bullet gem to solve the N+1 problem.
Screen Shot 2023-04-13 at 1 12 50 PM

- [x] In your PR description include the screenshots of your app's logs before and after the fix.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lojacho** [comment]
Hello @t-yanick as required I implemented the suggestions and also You can see the SS required: 

issuesN1

n+1resolved

Thanks for the feedback

**Review by rustam-tolipov — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Developer-512px-10

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
